{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csi-e2enetworks.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-e2enetworks.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ required "e2e.apiKey is required" .Values.e2e.apiKey | quote }}
  authToken: {{ required "e2e.authToken is required" .Values.e2e.authToken | quote }}
  projectID: {{ required "e2e.projectID is required" .Values.e2e.projectID | quote }}
{{- end }}
